# Generated by Django 2.2 on 2019-06-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(max_length=250)),
                ('type2', models.CharField(max_length=250)),
                ('type3', models.CharField(max_length=250)),
                ('type4', models.CharField(max_length=250)),
            ],
        ),
    ]
