# Generated by Django 2.2 on 2019-06-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_opt',
            name='type2',
        ),
        migrations.RemoveField(
            model_name='donation_opt',
            name='type3',
        ),
        migrations.RemoveField(
            model_name='donation_opt',
            name='type4',
        ),
    ]
